[cartridge]
publisher_id = 0x00
game_id = 0
game_version = 0

save_type = "NONE"
color = false
rtc = false
vertical = false

# mapper = "2003"
# rom_speed = 1
# rom_bus_width = 16

[memory.layout]
irq_vectors = [ 0x0000, 0x003F ]
c_heap = [ 0x0040, 0x0FFF ]
chip8 = [ 0x1000, 0x1FFF ]
screen1 = [ 0x3000, 0x37FF ]
screen2 = [ 0x3800, 0x3FFF ]
